"""initial migration

Revision ID: 961637651547
Revises: 
Create Date: 2025-04-03 09:45:38.633270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961637651547'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('company', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('p_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('cost_estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('awg_total', sa.Float(), nullable=True),
    sa.Column('conduit_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_estimations_project_id'), 'cost_estimations', ['project_id'], unique=False)
    op.create_table('labor_cost_estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chargers_count', sa.Integer(), nullable=True),
    sa.Column('charger_price', sa.Float(), nullable=True),
    sa.Column('labor_total', sa.Float(), nullable=True),
    sa.Column('low_voltage_total', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_cost_estimations_project_id'), 'labor_cost_estimations', ['project_id'], unique=False)
    op.create_table('misc_equipment_estimations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('misc_total', sa.Float(), nullable=True),
    sa.Column('equipment_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misc_equipment_estimations_project_id'), 'misc_equipment_estimations', ['project_id'], unique=False)
    op.create_table('project_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awg_base_cost', sa.Float(), nullable=True),
    sa.Column('awg_markup', sa.Float(), nullable=True),
    sa.Column('awg_subtotal', sa.Float(), nullable=True),
    sa.Column('awg_profit', sa.Float(), nullable=True),
    sa.Column('conduit_base_cost', sa.Float(), nullable=True),
    sa.Column('conduit_markup', sa.Float(), nullable=True),
    sa.Column('conduit_subtotal', sa.Float(), nullable=True),
    sa.Column('conduit_profit', sa.Float(), nullable=True),
    sa.Column('misc_base_cost', sa.Float(), nullable=True),
    sa.Column('misc_markup', sa.Float(), nullable=True),
    sa.Column('misc_subtotal', sa.Float(), nullable=True),
    sa.Column('misc_profit', sa.Float(), nullable=True),
    sa.Column('equipment_base_cost', sa.Float(), nullable=True),
    sa.Column('equipment_markup', sa.Float(), nullable=True),
    sa.Column('equipment_subtotal', sa.Float(), nullable=True),
    sa.Column('equipment_profit', sa.Float(), nullable=True),
    sa.Column('labor_base_cost', sa.Float(), nullable=True),
    sa.Column('labor_markup', sa.Float(), nullable=True),
    sa.Column('labor_subtotal', sa.Float(), nullable=True),
    sa.Column('labor_profit', sa.Float(), nullable=True),
    sa.Column('low_voltage_base_cost', sa.Float(), nullable=True),
    sa.Column('low_voltage_markup', sa.Float(), nullable=True),
    sa.Column('low_voltage_subtotal', sa.Float(), nullable=True),
    sa.Column('low_voltage_profit', sa.Float(), nullable=True),
    sa.Column('permits_base_cost', sa.Float(), nullable=True),
    sa.Column('permits_markup', sa.Float(), nullable=True),
    sa.Column('permits_subtotal', sa.Float(), nullable=True),
    sa.Column('permits_profit', sa.Float(), nullable=True),
    sa.Column('tax_base_cost', sa.Float(), nullable=True),
    sa.Column('tax_percentage', sa.Float(), nullable=True),
    sa.Column('tax_subtotal', sa.Float(), nullable=True),
    sa.Column('overhead_base_cost', sa.Float(), nullable=True),
    sa.Column('overhead_percentage', sa.Float(), nullable=True),
    sa.Column('overhead_subtotal', sa.Float(), nullable=True),
    sa.Column('grand_subtotal', sa.Float(), nullable=True),
    sa.Column('grand_total', sa.Float(), nullable=True),
    sa.Column('price_per_charger', sa.Float(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('total_submitted', sa.Float(), nullable=True),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_summaries_project_id'), 'project_summaries', ['project_id'], unique=False)
    op.create_table('estimation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('notes_awg', sa.String(length=300), nullable=True),
    sa.Column('notes_conduit', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('cost_estimation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cost_estimation_id'], ['cost_estimations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estimation_entries_cost_estimation_id'), 'estimation_entries', ['cost_estimation_id'], unique=False)
    op.create_table('labor_cost_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('workers', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('days', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('labor_cost_estimation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['labor_cost_estimation_id'], ['labor_cost_estimations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('misc_equipment_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('notes_misc', sa.String(length=300), nullable=True),
    sa.Column('notes_equip', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('misc_equipment_estimation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['misc_equipment_estimation_id'], ['misc_equipment_estimations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('misc_equipment_entries')
    op.drop_table('labor_cost_entries')
    op.drop_index(op.f('ix_estimation_entries_cost_estimation_id'), table_name='estimation_entries')
    op.drop_table('estimation_entries')
    op.drop_index(op.f('ix_project_summaries_project_id'), table_name='project_summaries')
    op.drop_table('project_summaries')
    op.drop_index(op.f('ix_misc_equipment_estimations_project_id'), table_name='misc_equipment_estimations')
    op.drop_table('misc_equipment_estimations')
    op.drop_index(op.f('ix_labor_cost_estimations_project_id'), table_name='labor_cost_estimations')
    op.drop_table('labor_cost_estimations')
    op.drop_index(op.f('ix_cost_estimations_project_id'), table_name='cost_estimations')
    op.drop_table('cost_estimations')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
