"""added new models and seeder data

Revision ID: 794749a31f9b
Revises: f75a30ca5f2a
Create Date: 2025-05-07 14:12:38.947446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794749a31f9b'
down_revision = 'a366dc8b3d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('construction_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conduit_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('price_per_foot', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['material_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'size', name='_supplier_size_uc')
    )
    with op.batch_alter_table('conduit_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conduit_prices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('construction_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['construction_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('union_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_apprentice', sa.Boolean(), nullable=True),
    sa.Column('apprentice_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('union_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wire_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('awg', sa.String(length=20), nullable=False),
    sa.Column('price_per_foot', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['material_suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'awg', name='_supplier_awg_uc')
    )
    with op.batch_alter_table('wire_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wire_prices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('union_wage_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('union_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['union_positions.id'], ),
    sa.ForeignKeyConstraint(['union_id'], ['unions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('union_id', 'position_id', 'effective_date', name='_union_position_date_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('union_wage_rates')
    with op.batch_alter_table('wire_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wire_prices_supplier_id'))

    op.drop_table('wire_prices')
    op.drop_table('union_positions')
    op.drop_table('construction_prices')
    with op.batch_alter_table('conduit_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conduit_prices_supplier_id'))

    op.drop_table('conduit_prices')
    op.drop_table('unions')
    op.drop_table('material_suppliers')
    op.drop_table('construction_materials')
    # ### end Alembic commands ###